### PR TITLE
nightly virus-scan-s3-buckets job: only notify slack for production

### PR DESCRIPTION
**Pull request by risicle**
We don't want to be woken by failures on preview.

### CODE REVIEW

**Comment by lfdebrux** [comment]
Are these guaranteed to fail on preview because of EICAR files?

**Comment by risicle** [comment]
No - those should get scanned and tagged thru their SNS notification. An already-tagged file will not be rescanned and not raise an alert.

**Comment by lfdebrux** [comment]
Hmm, so we should expect the tests to not fail most of the time?

**Comment by risicle** [comment]
The tests assert the behaviour of the SNS loop - they look for the (dummy) email sent as a result of the SNS message being processed. The catchup script failed on friday night because i'd been dicking with the av-api on friday making it miss certain SNS messages, leaving some eicar-ed files untagged.

**Comment by lfdebrux** [comment]
If we're not expecting the tests to fail often then I'm happy for the notifications to remain; I think it is up to devs to make sure they have their phones off during off-hours 😜

**Comment by risicle** [comment]
My point is that this is for preview, where the primary cause of "failure" will be due to people dicking around with it during the previous day. Not something that's a second line issue.

I'm half tempted to remove the slack alert entirely, because found viruses result in an email going to the mailing list anyway, whether triggered by SNS or the script.

**Comment by lfdebrux** [comment]
I see your point.

It should probably be only for preview though; currently this PR also changes staging as I understand it?

**Comment by katstevens** [comment]
> I'm half tempted to remove the slack alert entirely, because found viruses result in an email going to the mailing list anyway, whether triggered by SNS or the script.

I think I said this before, but we won't get an email if there's a failure executing the script itself (or sending the email, or git failing to checkout the repo properly). So keep the slack alert 😸

**Comment by risicle** [comment]
Uh yeah ok.

**Comment by risicle** [comment]
@katstevens indeed, but we don't have slack alerts for *all* our nightly jobs do we?

**Comment by katstevens** [comment]
We do for pretty much all our email scripts, indexing and data export jobs (for `condition: UNSTABLE_OR_WORSE`).

**Comment by risicle** [comment]
Oh ok fine. Keeping for staging & prod.

**Pull request merged**
