### PR TITLE
Revert "Work around for jenkins_plugin module bug"

### PR DESCRIPTION
**Pull request by lfdebrux**
This reverts commit 0ab15b94b53b19ea3b3e115af45b36da1b2ce458.

Closes https://trello.com/c/Ne3rA9In/

### Applying

This will need to be applied by running `make jenkins TAGS=jenkins` and restarting the Jenkins EC2 instance.

### Testing

We can then test it worked by running `make jenkins TAGS=plugins` and making sure we get no errors from the `jenkins_plugin` steps.

### CODE REVIEW

**Comment by katstevens** [comment]
How are we going to test that everything now works ok without the workaround?

**Comment by lfdebrux** [comment]
> How are we going to test that everything now works ok without the workaround?

I've updated the PR description with this info

**Comment by lfdebrux** [comment]
I've applied this to Jenkins successfully, and when running `make jenkins TAGS=plugins` I don't get the `No valid crumb` error we were seeing before, but I do get a different error 😥 

```
PLAY [Setup Jenkins CI, config and dependencies] ***************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************
ok: [ci.marketplace.team]

TASK [jenkins : Check if Github OAuth is set up yet so we can use the correct credentials] *********************************************************
ok: [ci.marketplace.team]

TASK [jenkins : Set credentials to jenkins github user if it exists] *******************************************************************************
ok: [ci.marketplace.team]

TASK [jenkins : Set credentials to admin user if jenkins github user does not exist] ***************************************************************
skipping: [ci.marketplace.team]

TASK [jenkins : Install plugins] *******************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: FileNotFoundError: [Errno 2] No such file or directory: b'/tmp/tmpki7g9i1r' -> b'/var/lib/jenkins/plugins/ansicolor.jpi'
failed: [ci.marketplace.team] (item=ansicolor) => {"ansible_loop_var": "item", "changed": false, "item": "ansicolor", "msg": "Could not replace file: /tmp/tmpki7g9i1r to /var/lib/jenkins/plugins/ansicolor.jpi: [Errno 2] No such file or directory: b'/tmp/tmpki7g9i1r' -> b'/var/lib/jenkins/plugins/ansicolor.jpi'"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: FileNotFoundError: [Errno 2] No such file or directory: b'/tmp/tmprcuem2x5' -> b'/var/lib/jenkins/plugins/audit-trail.jpi'
failed: [ci.marketplace.team] (item=audit-trail) => {"ansible_loop_var": "item", "changed": false, "item": "audit-trail", "msg": "Could not replace file: /tmp/tmprcuem2x5 to /var/lib/jenkins/plugins/audit-trail.jpi: [Errno 2] No such file or directory: b'/tmp/tmprcuem2x5' -> b'/var/lib/jenkins/plugins/audit-trail.jpi'"
```

**Comment by lfdebrux** [comment]
> I've applied this to Jenkins successfully, and when running `make jenkins TAGS=plugins` I don't get the `No valid crumb` error we were seeing before, but I do get a different error 😥

I get the same error  with or without this PR applied to Jenkins 🤔

**Comment by lfdebrux** [comment]
> > I've applied this to Jenkins successfully, and when running `make jenkins TAGS=plugins` I don't get the `No valid crumb` error we were seeing before, but I do get a different error 😥
> 
> I get the same error with or without this PR applied to Jenkins 🤔

I think the problem is that the [`jenkins_plugin` Ansible module](https://docs.ansible.com/ansible/latest/modules/jenkins_plugin_module.html) is trying to copy plugins to the Jenkins home directory `/var/lib/jenkins` (and expecting a folder `plugins` there) when in fact it should be copying to the Jenkins installation directory `/data/jenkins`.

It's not clear to me why it would have worked before though...

**Comment by lfdebrux** [comment]
> It's not clear to me why it would have worked before though...

Looking at the creation date of the current Jenkins EC2 instance (2019/07/11) and the last commit date of the plugins job (2019/07/12) it's possible we (I) didn't fully test it 😬 😅 😂

**Comment by lfdebrux** [comment]
Adding `jenkins_home: "{{ jenkins_data_dir }}"` to the `jenkins_plugin` step works without this PR applied.

**Comment by lfdebrux** [comment]
I've added the fix for `jenkins_plugin` to this PR, pushed it to Jenkins and tested it without issues.

Going to merge this PR now.

**Pull request merged**
